# SITE SETTINGS
title: Digilog
author: Vangelis Malamas

url: "https://bagmalamas.github.io"
baseurl: "/Digilog"

remote_theme: peterdesmet/petridish@3.1

# IMPORTANT: point to YOUR custom CSS file
custom_css: /assets/theme/css/custom.css

logo: /assets/theme/images/digilog-logo.png

# SOCIAL PROFILES
social:
  email: name@example.com
  github: bagmalamas

# THEME SETTINGS (OPTIONAL)
posts_on_home: 2
archive_permalink: /blog/
github_edit: true
colors:
  links: "#007bff"
  banner: "#007bff"
  footer: "#6c757d"
font_serif: true
rounded_corners: true

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - jekyll-theme-petridish.gemspec
  - CITATION.cff

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: posts
    values:
      permalink: "/blog/:year/:slug/"
